### ISSUE TITLE
window is not defined after installing module

### ISSUE THREAD

**Issue by Simerjit-developer** [opentok/accelerator-textchat-js#36]
I am working in node js. I installed opentok-text-chat using npm. Then I started using node server.js, it returns following error:

```
E:\simerjit\dawai\node_modules\opentok-text-chat\dist\opentok-text-chat.js:14
    window.jQuery = $;
    ^

ReferenceError: window is not defined
    at Object.<anonymous> (E:\simerjit\dawai\node_modules\opentok-text-chat\dist
\opentok-text-chat.js:14:5)
    at Object.<anonymous> (E:\simerjit\dawai\node_modules\opentok-text-chat\dist
\opentok-text-chat.js:608:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:\simerjit\dawai\server\routes.js:28:32)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)

```

**Comment by msach22** [comment]
@Simerjit-developer The opentok-text-chat is a client-side library, you cannot run it as a server-side library.

More info here: https://stackoverflow.com/questions/48163489/window-is-not-defined-in-opentok-text-chat-node-module

cc: @maikthomas
